apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d5bguum6i-nodejs 
  janus-idp.io/tekton: d5bguum6i-nodejs
  backstage.io/kubernetes-id: d5bguum6i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d5bguum6i-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  